In [1]:
import numpy as np
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt

In [2]:
documents = ["I like deep learning.", 
                "I like NLP.",
                "I enjoy flying." 
            ]

In [3]:
def extract_token(docs):
    list_token = []
    for d in docs:
        list_token.extend(word_tokenize(d)) # bad solution, why?

    list_token = list(set(list_token))
    return list_token

In [4]:
# a bad solution, ie should be improved
def cal_co_occ(sentence, list_token, co_occ, window=2):
    for i, word in enumerate(sentence):
        for j in range(max(i-window,0), min(i+window, len(sentence))):
            if i != j:
                co_occ[list_token.index(word),list_token.index(sentence[j])] += 1


In [5]:
tokens = extract_token(documents)
print(tokens)

['I', 'flying', '.', 'NLP', 'enjoy', 'deep', 'like', 'learning']


In [6]:
co_occ = np.zeros((len(tokens), len(tokens)))
for d in documents:
    cal_co_occ(d.replace('.', ' .').split(), tokens, co_occ)


In [7]:
print(co_occ)

[[0. 0. 0. 0. 1. 0. 2. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 1.]
 [2. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0.]]
